require_relative './sliding_piece.rb'
require_relative './stepping_piece.rb'
require_relative './piece.rb'
require_relative './pawn.rb'
require_relative './knight.rb'
require_relative './king.rb'
require_relative './board.rb'
